### PR TITLE
Separator is now a true separator (a line instead of a space).

### PR DESCRIPTION
**Pull request by fgallaire**

### CODE REVIEW

**Comment by lesteve** [comment]
Thanks a lot for taking some time to improve formlayout ! Quickly looking at it most of your PRs seem to make a lot of sense.

Out of curiosity, are you using formlayout for some of your projects?

Also if you are familiar with Travis, it would be great to invest some time fixing the Travis setup so that we can have green checkmarks on PR. I started working on it a while ago but never found the time to finish it. Some of the continuous integration seem to be taken straight from spyder and my feeling was that there were a lot of reasonably complicated things that we probably don't need.

**Comment by fgallaire** [comment]
@lesteve yes I would like to use formlayout in some projects. First of all to do a KISS Qt version of the txt2tags Tkinter GUI.

As I said to @PierreRaybaut by email, I know nothing about Travis and don't have time to learn about it now :-(

**Comment by lesteve** [comment]
> As I said to @PierreRaybaut by email, I know nothing about Travis and don't have time to learn about it now :-(

Fair enough, I'll try to resuscitate the work on Travis I started a while ago ...

In the longer term I would definitely encourage you to take a look of Travis for your projects. It's very convenient to have continuous integration on PRs and test a variety of setups (e.g. python or package versions).

Also just FYI, there is some plan for formlayout to have Tk support in the medium term.

**Comment by fgallaire** [comment]
> Also just FYI, there is some plan for formlayout to have Tk support in the medium term.

Tk is not really the lib of the future ^^, but I understand the value to support the only GUI of the standard lib.

If integration of multiple backends in formlayout is possible, I'm interested in working on a TUI one based on [npyscreen](npyscreen.readthedocs.org/introduction.html).

**Comment by lesteve** [comment]
> If integration of multiple backends in formlayout is possible, I'm interested in working on a TUI one based on npyscreen.

Nice, I never heard about npyscreen to be honest. The reason we want Tk support is so that it works with python without additional package. In our experience, reducing dependencies is a must to increase package adoption and reduce maintenance costs. I don't think it's reasonable starting supporting more backends that early in the life of formlayout. Having said that, maybe the work on Tk support will make it easier to support other backends in the long term.

**Comment by fgallaire** [comment]
One other option is to build a new lib with formlayout as a Qt backend, and build the nodeps Tk backend and the npyscreen as new backends of the new lib.

And this fix #10 as we can choose the sexy name we want for the new lib.

**Pull request merged**
