### PR TITLE
Add ok, cancel and apply_ options to configure the buttons

### PR DESCRIPTION
**Pull request by fgallaire**

### CODE REVIEW

**Comment by lesteve** [comment]
It would be great to rebase all your PRs on master so that Travis goes green. Also using your new feature in one of the examples (simple.py or advanced.py) would be very welcome so that we have a very minimal test.

Another minor comment: in general please try to fill the description, even with a single sentence, to explain the motivation behind the PR.

**Comment by PierreRaybaut** [comment]
@fgallaire: I agree with @lesteve on this one. The motivation of the PR is unclear (at least for me, when reading the code rapidly). Also, I'm not a huge fan of introducing new features without adding the associated test.

**Comment by fgallaire** [comment]
As  said before, my first project is to replace the txt2tags Tkinter GUI:
http://txt2tags.org/userguide/gui.png
As you can see on the screenshot, I need to theme the Apply and Cancel buttons messages.

More generaly, this is a good way to customize the UI so to make formlayout suitable for little real apps.

And to improve this, the **options dict is a good way to add new conf features whitout changing API.

**Comment by lesteve** [comment]
> As you can see on the screenshot, I need to theme the Apply and Cancel buttons messages.

Can you use this feature in examples/advanced.py? That would be an easy way to show how it is used and test it.

**Pull request merged**
