### PR TITLE
Replace font exception by a warning

### PR DESCRIPTION
**Pull request by fgallaire**

### CODE REVIEW

**Comment by PierreRaybaut** [comment]
Could you please explain why is it necessary to ignore this error?

**Comment by fgallaire** [comment]
@PierreRaybaut 
An exception stop the program !
A warning would be a best fit for the users.

**Comment by PierreRaybaut** [comment]
I understand that but I still don't see the use case. Why would a user want to ignore the fact that the default font is not installed? It seems rather blocking for me as it will raise the mysterious error message (issue #19) afterwards.

**Comment by fgallaire** [comment]
Test it, there's no more mysterious message but a working FontLayout because of your other line change.

**Comment by PierreRaybaut** [comment]
Oh, I see, you're right. I'm merging it and adding `file=sys.stderr` in the print function call.

**Pull request merged**
