### PR TITLE
[MRG] Set up Travis integration

### PR DESCRIPTION
**Pull request by lesteve**
This should get Travis green.

Main changes are:
- Simplify install.sh in particular always use conda
- formlayout.py needs Arial font to be installed
- Remove build_test.sh since I am not sure what its purpose is

@PierreRaybaut should we test PySide as well (probably in a different PR)? I have to say my experience with Qt/PyQt is almost non existent ...

### CODE REVIEW

**Comment by lesteve** [comment]
@PierreRaybaut it would be great to merge this one, since that would allow to merge other pending PRs with a bit more confidence.

**Comment by lesteve** [comment]
Let me know if you have comments!

**Comment by PierreRaybaut** [comment]
Thanks a lot for taking the time to fix this... as commented elsewhere, implementing Travis support was unfinished business.

**Comment by PierreRaybaut** [comment]
@lesteve PySide should be tested indeed, ideally.

**Pull request merged**
