### PR TITLE
Add background_color and widget_color theming options

### PR DESCRIPTION
**Pull request by fgallaire**

### CODE REVIEW

**Comment by PierreRaybaut** [comment]
Quick question: what is the meaning of "wgt" in "**_wgt_**_color"?

And something's wrong when testing with Python 3.4.4 64bits PyQt4 4.11.4 on Windows:

``` python
Traceback (most recent call last):
  File "C:\Python\formlayout\examples\advanced.py", line 86, in <module>
    wgt_color='#cf9'))
  File "C:\Python\formlayout\formlayout.py", line 1155, in fedit
    result, outfile, type, scrollbar, bgd_color, wgt_color)
  File "C:\Python\formlayout\formlayout.py", line 961, in __init__
    self.formwidget.setup()
  File "C:\Python\formlayout\formlayout.py", line 662, in setup
    field.setStyleSheet("background-color:" + self.wgt_color + ";")
AttributeError: 'SliderLayout' object has no attribute 'setStyleSheet'
```

**Comment by PierreRaybaut** [comment]
Same traceback with Python 3.5.2 64bits, PyQt5 5.6 on Windows

**Comment by fgallaire** [comment]
wgt_color for widget color

I have merged #64 so this should be OK.

**Comment by PierreRaybaut** [comment]
Ok for this PR. 👍 

Two remarks though:
1. The "formlayout.py" symbolic link breaks the "advanced.py" example on Windows: it has to be removed and another solution to be found to fix the associated Travis bug (if any).
2. The "wgt_color" option/argument has to be renamed, to comply with Python zen rule "Explicit is better than implicit.". I suggest renaming to "widget_color", even if it's slightly longer, it will be explicit.

**Comment by PierreRaybaut** [comment]
Same remark regarding "bgd_color" (even if it's easier to guess that it's short for "background_color") and "req_color":
- bgd_color --> background_color
- req_color --> required_color (if that's correct)

**Comment by fgallaire** [comment]
Renaming just the options, or the variable names inside the code too ?

**Comment by PierreRaybaut** [comment]
Yes, I'm ok with this PR as long as those 3 references are renamed and the symbolic link is removed (or open an issue for this last one).

**Pull request merged**
